const std = @import("std");

pub const JuceModule = enum {
    juce_analytics,
    juce_animation,
    juce_audio_basics,
    juce_audio_devices,
    juce_audio_formats,
    juce_audio_processors,
    juce_audio_processors_headless,
    juce_audio_utils,
    juce_build_tools,
    juce_box2d,
    juce_core,
    juce_cryptography,
    juce_data_structures,
    juce_dsp,
    juce_events,
    juce_graphics,
    juce_gui_basics,
    juce_gui_extra,
    juce_javascript,
    juce_midi_ci,
    juce_opengl,
    juce_osc,
    juce_product_unlocking,
    juce_video,
};

pub const modules = [_]type{
    @import("modules/juce_analytics.zig"),
    @import("modules/juce_animation.zig"),
    @import("modules/juce_audio_basics.zig"),
    @import("modules/juce_audio_devices.zig"),
    @import("modules/juce_audio_formats.zig"),
    @import("modules/juce_audio_processors.zig"),
    @import("modules/juce_audio_processors_headless.zig"),
    @import("modules/juce_audio_utils.zig"),
    @import("modules/juce_box2d.zig"),
    @import("modules/juce_build_tools.zig"),
    @import("modules/juce_core.zig"),
    @import("modules/juce_cryptography.zig"),
    @import("modules/juce_data_structures.zig"),
    @import("modules/juce_dsp.zig"),
    @import("modules/juce_events.zig"),
    @import("modules/juce_graphics.zig"),
    @import("modules/juce_gui_basics.zig"),
    @import("modules/juce_gui_extra.zig"),
    @import("modules/juce_javascript.zig"),
    @import("modules/juce_midi_ci.zig"),
    @import("modules/juce_opengl.zig"),
    @import("modules/juce_osc.zig"),
    @import("modules/juce_product_unlocking.zig"),
    @import("modules/juce_video.zig"),
};
